"""empty message

Revision ID: 038cab0ed6a9
Revises: a08d70196c42
Create Date: 2017-09-18 15:35:16.197068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '038cab0ed6a9'
down_revision = 'a08d70196c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flasky_configs', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.drop_column('flasky_configs', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flasky_configs', sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('flasky_configs', 'password_hash')
    # ### end Alembic commands ###
