"""empty message

Revision ID: 1f1a6727e09e
Revises: a601cdb6c045
Create Date: 2017-09-27 23:44:32.101676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f1a6727e09e'
down_revision = 'a601cdb6c045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flasky_articles', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flasky_articles', sa.Column('test', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
