"""empty message

Revision ID: 4506b6b4bd9d
Revises: 1f1a6727e09e
Create Date: 2017-09-27 23:46:24.081497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4506b6b4bd9d'
down_revision = '1f1a6727e09e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flasky_articles', sa.Column('visits', sa.Integer(), nullable=True))
    op.drop_column('flasky_articles', 'views')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flasky_articles', sa.Column('views', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('flasky_articles', 'visits')
    # ### end Alembic commands ###
