"""empty message

Revision ID: baf7cd7f2c57
Revises: 4506b6b4bd9d
Create Date: 2017-09-27 23:47:34.670277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'baf7cd7f2c57'
down_revision = '4506b6b4bd9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flasky_articles', sa.Column('views', sa.Integer(), nullable=True))
    op.drop_column('flasky_articles', 'visits')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flasky_articles', sa.Column('visits', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('flasky_articles', 'views')
    # ### end Alembic commands ###
